backends:
  - url: http://localhost:8080
    weight: 3
  - url: http://localhost:7070
    weight: 1
health_check_path: /health
strategy: weighted
error_rate: 0.0
sticky_cookie: "STICKY_SESSION"
request_timeout: 2s
max_retries: 2

rate_limit:
  per_client:
    rate: 100 # tokens per second
    capacity: 200 # bucket size
  per_backend:
    rate: 300
    capacity: 500
